language: node_js
dist: trusty

node_js: '12'
cache: npm

before_install: cd frontend

install:
  - npm i

script:
  - CI=false npm run build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: jwc.quinton.pizza
  local_dir: build
  acl: public_read
  region: us-west-2
  skip_cleanup: true
  on:
    branch: master

